[build]
  command = "npx directus build"      # Command to build Directus Admin Panel
  publish = "public"                   # Directory containing the built files from Directus

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"
